const MD='https://api.mangadex.org';
const AI='https://ai-gateway.vercel.sh/v1/chat/completions';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const UA='PanelTranslate/3.0';
const VISION=process.env.VISION_MODEL||'google/gemini-3.6-flash';
const TRANSLATE=process.env.TRANSLATION_MODEL||'openai/gpt-5.6-sol';
const WORKER=String(process.env.MANGA_WORKER_URL||'').replace(/\/+$/,'');
const WORKER_TOKEN=process.env.MANGA_WORKER_TOKEN||'';
const clamp=(n,a,b)=>Number.isFinite(+n)?Math.min(b,Math.max(a,+n)):a;
const box=(b={})=>{const o={x:clamp(b.x,0,100),y:clamp(b.y,0,100),w:clamp(b.w,.2,100),h:clamp(b.h,.2,100)};o.x=Math.min(o.x,100-o.w);o.y=Math.min(o.y,100-o.h);return o};
const hex=(v,d)=>/^#[0-9a-f]{6}$/i.test(String(v||''))?String(v):d;
function token(req){return process.env.AI_GATEWAY_API_KEY||req.headers?.['x-vercel-oidc-token']||process.env.VERCEL_OIDC_TOKEN||''}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>1_500_000)throw Error('Requisição grande demais.')}return s?JSON.parse(s):{}}
async function page(chapterId,index){const h=await fetch(`${MD}/at-home/server/${chapterId}`,{headers:{Accept:'application/json','User-Agent':UA}});if(!h.ok)throw Error(`MangaDex@Home falhou (${h.status}).`);const j=await h.json(),f=j.chapter?.data?.[index];if(!j.baseUrl||!j.chapter?.hash||!f)throw Error('Página não encontrada.');const r=await fetch(`${j.baseUrl}/data/${j.chapter.hash}/${encodeURIComponent(f)}`,{headers:{'User-Agent':UA}});if(!r.ok)throw Error(`Falha ao baixar a página (${r.status}).`);const buf=Buffer.from(await r.arrayBuffer());if(buf.length>18*1024*1024)throw Error('Página grande demais para análise.');return{buf,type:r.headers.get('content-type')||'image/jpeg'}}
const B={type:'object',additionalProperties:false,properties:{x:{type:'number'},y:{type:'number'},w:{type:'number'},h:{type:'number'}},required:['x','y','w','h']};
const S={type:'object',additionalProperties:false,properties:{orientation:{type:'string',enum:['horizontal','vertical']},align:{type:'string',enum:['left','center','right']},role:{type:'string',enum:['dialogue','narration','shout','whisper','sfx','handwritten','system']},weight:{type:'integer'},italic:{type:'boolean'},uppercase:{type:'boolean'},textColor:{type:'string'},strokeColor:{type:'string'},strokeWidth:{type:'number'},letterSpacing:{type:'number'},lineHeight:{type:'number'}},required:['orientation','align','role','weight','italic','uppercase','textColor','strokeColor','strokeWidth','letterSpacing','lineHeight']};
const VSC={type:'object',additionalProperties:false,properties:{detectedLanguage:{type:'string'},pageSummary:{type:'string'},blocks:{type:'array',items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},original:{type:'string'},type:{type:'string',enum:['dialogue','narration','sfx','caption','sign','other']},readingOrder:{type:'integer'},textBox:B,containerBox:B,containerDetected:{type:'boolean'},rotation:{type:'number'},confidence:{type:'number'},needsReview:{type:'boolean'},eraseMode:{type:'string',enum:['flat','simple','complex','none']},backgroundColor:{type:'string'},style:S},required:['id','original','type','readingOrder','textBox','containerBox','containerDetected','rotation','confidence','needsReview','eraseMode','backgroundColor','style']}}},required:['detectedLanguage','pageSummary','blocks']};
const TSC={type:'object',additionalProperties:false,properties:{pageSummaryPt:{type:'string'},glossary:{type:'array',items:{type:'object',additionalProperties:false,properties:{source:{type:'string'},target:{type:'string'}},required:['source','target']}},blocks:{type:'array',items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},translated:{type:'string'},confidence:{type:'number'},note:{type:'string'}},required:['id','translated','confidence','note']}}},required:['pageSummaryPt','glossary','blocks']};
async function gateway(auth,model,messages,schema,max=12000){const r=await fetch(AI,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth}`},body:JSON.stringify({model,messages,temperature:.08,max_tokens:max,response_format:{type:'json_schema',json_schema:{name:'panel_translate',strict:true,schema}}})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j?.error?.message||`AI Gateway falhou (${r.status}).`);const c=j?.choices?.[0]?.message?.content;if(!c)throw Error('A IA não retornou conteúdo.');return typeof c==='string'?JSON.parse(c):c}
function ctxText(c={}){const g=Array.isArray(c.glossary)?c.glossary.slice(-50):[],h=Array.isArray(c.history)?c.history.slice(-70):[];return [c.summary?`Resumo anterior: ${c.summary}`:'',g.length?`Glossário:\n${g.map(x=>`${x.source} => ${x.target}`).join('\n')}`:'',h.length?`Trechos anteriores:\n${h.map(x=>`${x.original} => ${x.translated}`).join('\n')}`:''].filter(Boolean).join('\n\n')||'(sem contexto anterior)'}
function vprompt(src){return `Você é um especialista em OCR, layout e lettering de scanlation. Analise TODA a página de mangá/manhwa/manhua sem traduzir. Idioma esperado: ${src||'auto'}.
Retorne um bloco por fala/narração/SFX/sign coerente. Coordenadas são percentuais 0..100.
textBox deve abraçar apenas os glifos; containerBox deve ser a área útil real do balão/caixa para receber a tradução. Identifique ordem de leitura, rotação e estilo visual.
Copie com precisão orientação, alinhamento, peso, itálico, caixa alta, cor, contorno, espaçamento e altura de linha.
eraseMode: flat=balão uniforme; simple=fundo pouco texturizado; complex=texto sobre desenho/cenário; none=apagar é arriscado. SFX integrado à arte normalmente é complex/none.
Nunca invente texto. Preserve pontuação, honoríficos, nomes, onomatopeias e intensidade. needsReview=true em qualquer dúvida.`}
function tprompt(layout,target,context){const ordered=[...(layout.blocks||[])].sort((a,b)=>a.readingOrder-b.readingOrder);return `Você é tradutor/editor profissional de scanlation. Traduza para ${target||'pt-BR'} mantendo intenção, personalidade, humor, formalidade, emoção e continuidade. Português brasileiro natural, não literal. Não invente informação. Nomes próprios só mudam se houver forma consagrada. Preserve pontuação e intensidade.
A tradução precisa CABER no mesmo balão: seja conciso sem perder sentido. SFX: use equivalente curto em PT-BR quando natural; caso contrário translitere de modo legível.
Use o contexto apenas para consistência.
${ctxText(context)}

Resumo visual: ${layout.pageSummary||''}

Blocos:\n${ordered.map(b=>`[${b.id}] ${b.type}: ${b.original}`).join('\n')}`}
function sanitize(l,t){const tm=new Map((t?.blocks||[]).map(x=>[String(x.id),x]));const blocks=(l?.blocks||[]).map((b,i)=>{const tr=tm.get(String(b.id))||{},s=b.style||{},conf=Math.min(clamp(b.confidence,0,1),clamp(tr.confidence??1,0,1));return{id:String(b.id||`b${i+1}`),original:String(b.original||'').trim(),translated:String(tr.translated||b.original||'').trim(),type:['dialogue','narration','sfx','caption','sign','other'].includes(b.type)?b.type:'other',readingOrder:Number.isFinite(+b.readingOrder)?+b.readingOrder:i,textBox:box(b.textBox),containerBox:box(b.containerBox),containerDetected:Boolean(b.containerDetected),rotation:clamp(b.rotation,-90,90),confidence:conf,needsReview:Boolean(b.needsReview)||conf<.72,eraseMode:['flat','simple','complex','none'].includes(b.eraseMode)?b.eraseMode:'none',backgroundColor:hex(b.backgroundColor,'#ffffff'),note:String(tr.note||''),style:{orientation:s.orientation==='vertical'?'vertical':'horizontal',align:['left','center','right'].includes(s.align)?s.align:'center',role:['dialogue','narration','shout','whisper','sfx','handwritten','system'].includes(s.role)?s.role:(b.type==='sfx'?'sfx':'dialogue'),weight:Math.round(clamp(s.weight,300,900)/100)*100,italic:Boolean(s.italic),uppercase:Boolean(s.uppercase),textColor:hex(s.textColor,'#111111'),strokeColor:hex(s.strokeColor,'#ffffff'),strokeWidth:clamp(s.strokeWidth,0,6),letterSpacing:clamp(s.letterSpacing,-.08,.25),lineHeight:clamp(s.lineHeight,.75,1.6)}}});return{detectedLanguage:String(l?.detectedLanguage||''),summary:String(t?.pageSummaryPt||l?.pageSummary||''),glossary:Array.isArray(t?.glossary)?t.glossary.slice(0,80):[],blocks:blocks.sort((a,b)=>a.readingOrder-b.readingOrder)}}
async function specialized(im,payload){if(!WORKER)return null;try{const r=await fetch(`${WORKER}/analyze`,{method:'POST',headers:{'Content-Type':'application/json',...(WORKER_TOKEN?{Authorization:`Bearer ${WORKER_TOKEN}`}:{})},body:JSON.stringify({image:`data:${im.type};base64,${im.buf.toString('base64')}`,sourceLanguage:payload.sourceLanguage,targetLanguage:payload.targetLanguage,context:payload.context})});if(!r.ok)return null;const j=await r.json();return j.analysis||null}catch{return null}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');try{if(req.method!=='POST')return res.status(405).json({ok:false,error:{message:'Use POST.'}});const p=await body(req);if(!UUID.test(p.chapterId||''))return res.status(400).json({ok:false,error:{message:'ID do capítulo inválido.'}});const index=Number(p.pageIndex);if(!Number.isInteger(index)||index<0)return res.status(400).json({ok:false,error:{message:'Índice da página inválido.'}});const im=await page(p.chapterId,index);const worker=await specialized(im,p);if(worker)return res.status(200).json({ok:true,analysis:worker,engine:'specialized-worker'});const auth=token(req);if(!auth)throw Error('OIDC/API key não disponível. Ative OIDC Federation no projeto Vercel ou configure AI_GATEWAY_API_KEY.');const data=`data:${im.type};base64,${im.buf.toString('base64')}`;const layout=await gateway(auth,VISION,[{role:'system',content:vprompt(p.sourceLanguage)},{role:'user',content:[{type:'text',text:'Analise esta página inteira e devolva somente o JSON solicitado.'},{type:'image_url',image_url:{url:data}}]}],VSC,14000);const translated=await gateway(auth,TRANSLATE,[{role:'system',content:tprompt(layout,p.targetLanguage,p.context)},{role:'user',content:'Traduza todos os blocos detectados, mantendo exatamente os mesmos ids.'}],TSC,12000);return res.status(200).json({ok:true,analysis:sanitize(layout,translated),engine:'ai-gateway',models:{vision:VISION,translation:TRANSLATE}})}catch(e){return res.status(500).json({ok:false,error:{message:e?.message||'Erro interno.'}})}}
